services:
  - type: web
    name: mmt-backend
    env: docker
    region: ohio
    plan: free
    repo: https://github.com/viniciosgnr/MMT
    branch: master
    rootDir: backend # Context for Docker build
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
